defaults: &defaults
  host: "127.0.0.1:9200"
  bootstrap: true

development:
  <<: *defaults
  index: development

test:
  <<: *defaults
  index: test

staging:
  <<: *defaults
  host: <%= Rails.application.credentials[:elasticsearch_host] %>
  index: staging

production:
  <<: *defaults
  host: <%= Rails.application.credentials[:elasticsearch_host] %>
  index: production
