:verbose: false

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
production:
  :concurrency: 5
  :labels:
    - critical
  :queues:
    - compraagil_production_mailers
    - compraagil_production_default

staging:
  :concurrency: 5
  :labels:
    - critical
  :queues:
    - compraagil_production_mailers
    - compraagil_production_default

development:
  :concurrency: 5
  :labels:
    - critical
  :queues:
    - compraagil_production_mailers
    - compraagil_production_default

